ability to use normal URL instead of sheetId only
emilianozublena/sheetsu-php pull request #8
Opened 2017-11-22 10:20 UTC by erbear

Hi there! 
It's Bartek from Sheetsu here. We are in the middle of setting up different analytics measures for our application. The plan includes measuring a number of hits from different languages and libraries. We want to know where our users are and where our attention should be. That is why I made following changes: 

1. I have added ability to use URL instead of only Sheetsu id
2. Changed a base URL so we can track from which library the request is coming

2017-11-22 12:28 UTC, emilianozublena requested changes
Please, avoid setting private parameters directly; you could change the _setSheetUrl() function to allow a parameter in which case that function should be the one setting the parameter.
Also, if possible, refactor those array_key_exists to be in one function like "_validateConfig" or something like that. We need to avoid having "independent" blocks for validation or iteration as to keep everything neet and maintainable.
If you can do this changes ill merge everything and set new tag release if not, let me know, im a little bit busy these days but ill find a moment...

2017-11-23 11:34 UTC, erbear commented
I have made the changes you requested. Let me know if everything is fine :)

2017-11-23 11:47 UTC, merged

2017-11-23 11:47 UTC, emilianozublena commented
Looks great, ill merge and release tag ;)

2017-11-23 13:34 UTC, jdrzj commented
🎉

2017-11-23 13:38 UTC, emilianozublena commented
Worldwide collaboration ftw!